CFLAGS = -Wall
CC = gcc

main: main.o

clean:
	rm -f main.o main

test:  main
	@echo -e "\n\nTESTING\n\n"
	./main /home/jakub/CLionProjects/sysopy/tests/KozlakSroda9:35/zad2 /home/jakub/CLionProjects/sysopy/tests/KozlakSroda9:35/zad2/main.c

all: main test